In [6]:
### Don't mind about this
import warnings
warnings.filterwarnings('ignore')
###

%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [7]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [24]:
df = pd.read_csv('/content/drive/Shareddrives/IML_Covid/Final.csv')

In [25]:
df.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DEAD,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL
0,2,1,1,1,1,1,65,2,2,2,2,2,1,2,2,2,2,2,3
1,2,1,2,1,1,1,72,2,2,2,2,2,1,2,2,1,1,2,4
2,2,1,2,2,1,2,55,2,1,2,2,2,2,2,2,2,2,2,3
3,2,1,1,1,1,2,53,2,2,2,2,2,2,2,2,2,2,2,4
4,2,1,2,1,1,2,68,2,1,2,2,2,1,2,2,2,2,2,3

In [26]:
columns_to_replace = df.columns.difference(['MEDICAL_UNIT', 'AGE', 'CLASIFFICATION_FINAL'])
df[columns_to_replace] = df[columns_to_replace].replace(2,0)
df.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DEAD,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL
0,0,1,1,1,1,1,65,0,0,0,0,0,1,0,0,0,0,0,3
1,0,1,0,1,1,1,72,0,0,0,0,0,1,0,0,1,1,0,4
2,0,1,0,0,1,0,55,0,1,0,0,0,0,0,0,0,0,0,3
3,0,1,1,1,1,0,53,0,0,0,0,0,0,0,0,0,0,0,4
4,0,1,0,1,1,0,68,0,1,0,0,0,1,0,0,0,0,0,3

In [27]:
units = pd.get_dummies(df['MEDICAL_UNIT'], prefix='MEDICAL_UNIT', dtype = int)
df = df.drop('MEDICAL_UNIT', axis= 1)
df = pd.concat([df, units], axis= 1)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 31 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   USMER                 1048575 non-null  int64
 1   SEX                   1048575 non-null  int64
 2   PATIENT_TYPE          1048575 non-null  int64
 3   DEAD                  1048575 non-null  int64
 4   PNEUMONIA             1048575 non-null  int64
 5   AGE                   1048575 non-null  int64
 6   PREGNANT              1048575 non-null  int64
 7   DIABETES              1048575 non-null  int64
 8   COPD                  1048575 non-null  int64
 9   ASTHMA                1048575 non-null  int64
 10  INMSUPR               1048575 non-null  int64
 11  HIPERTENSION          1048575 non-null  int64
 12  OTHER_DISEASE         1048575 non-null  int64
 13  CARDIOVASCULAR        1048575 non-null  int64
 14  OBESITY               1048575 non-null  int64
 15  RENAL_CHRONIC         1048575 non-null  int64
 16  TOBACCO               1048575 non-null  int64
 17  CLASIFFICATION_FINAL  1048575 non-null  int64
 18  MEDICAL_UNIT_1        1048575 non-null  int64
 19  MEDICAL_UNIT_2        1048575 non-null  int64
 20  MEDICAL_UNIT_3        1048575 non-null  int64
 21  MEDICAL_UNIT_4        1048575 non-null  int64
 22  MEDICAL_UNIT_5        1048575 non-null  int64
 23  MEDICAL_UNIT_6        1048575 non-null  int64
 24  MEDICAL_UNIT_7        1048575 non-null  int64
 25  MEDICAL_UNIT_8        1048575 non-null  int64
 26  MEDICAL_UNIT_9        1048575 non-null  int64
 27  MEDICAL_UNIT_10       1048575 non-null  int64
 28  MEDICAL_UNIT_11       1048575 non-null  int64
 29  MEDICAL_UNIT_12       1048575 non-null  int64
 30  MEDICAL_UNIT_13       1048575 non-null  int64
dtypes: int64(31)
memory usage: 248.0 MB
None

In [28]:
print(df['AGE'].unique())

[ 65  72  55  53  68  40  64  37  25  38  24  30  48  23  80  61  54  59
  45  26  32  49  39  27  57  20  56  47  50  46  43  28  33  16  62  58
  36  44  66  52  51  35  19  90  34  22  29  14  31  42  15   1   0  17
  41   2  10  12  13   4   7   6   8  60   5  63  75  81  67  18  70  88
  85  92  73  74  78  76  82  77  86  71  95  87  83  84  79  69  89   3
  97  93 100  91  21 103  11   9  94  96 101 107 102  98  99 109 119 116
 105 104 111 114 120 106 108 110 118 117 121 115 113]

In [29]:
for f in df.columns:
  print(df[f].value_counts(), end = "\n\n")

USMER
0    662903
1    385672
Name: count, dtype: int64

SEX
1    525064
0    523511
Name: count, dtype: int64

PATIENT_TYPE
1    848544
0    200031
Name: count, dtype: int64

DEAD
0    971633
1     76942
Name: count, dtype: int64

PNEUMONIA
0    904745
1    143830
Name: count, dtype: int64

AGE
30     27010
31     25927
28     25313
29     25134
34     24872
       ...
114        2
116        2
111        1
121        1
113        1
Name: count, Length: 121, dtype: int64

PREGNANT
0    1037878
1      10697
Name: count, dtype: int64

DIABETES
0    922132
1    126443
Name: count, dtype: int64

COPD
0    1032312
1      16263
Name: count, dtype: int64

ASTHMA
0    1016089
1      32486
Name: count, dtype: int64

INMSUPR
0    1032962
1      15613
Name: count, dtype: int64

HIPERTENSION
0    884437
1    164138
Name: count, dtype: int64

OTHER_DISEASE
0    1018455
1      30120
Name: count, dtype: int64

CARDIOVASCULAR
0    1026423
1      22152
Name: count, dtype: int64

OBESITY
0    887181
1    161394
Name: count, dtype: int64

RENAL_CHRONIC
0    1028498
1      20077
Name: count, dtype: int64

TOBACCO
0    962173
1     86402
Name: count, dtype: int64

CLASIFFICATION_FINAL
4    656596
3    381527
1      8601
2      1851
Name: count, dtype: int64

MEDICAL_UNIT_1
0    1048424
1        151
Name: count, dtype: int64

MEDICAL_UNIT_2
0    1048406
1        169
Name: count, dtype: int64

MEDICAL_UNIT_3
0    1029400
1      19175
Name: count, dtype: int64

MEDICAL_UNIT_4
0    734170
1    314405
Name: count, dtype: int64

MEDICAL_UNIT_5
0    1041331
1       7244
Name: count, dtype: int64

MEDICAL_UNIT_6
0    1007991
1      40584
Name: count, dtype: int64

MEDICAL_UNIT_7
0    1047684
1        891
Name: count, dtype: int64

MEDICAL_UNIT_8
0    1038176
1      10399
Name: count, dtype: int64

MEDICAL_UNIT_9
0    1010459
1      38116
Name: count, dtype: int64

MEDICAL_UNIT_10
0    1040702
1       7873
Name: count, dtype: int64

MEDICAL_UNIT_11
0    1042998
1       5577
Name: count, dtype: int64

MEDICAL_UNIT_12
1    602995
0    445580
Name: count, dtype: int64

MEDICAL_UNIT_13
0    1047579
1        996
Name: count, dtype: int64

In [30]:
df.to_csv('/content/drive/Shareddrives/IML_Covid/recovered_Covid.csv', index= False)